#check .env file for variables/values
version: "3.9"
services:
  db:
    image: "${IMAGE_NAME}"
    container_name: "${CONTAINER_NAME}"
    ports:
      - "${PORT_MAP}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - ${HOST_DB_PATH}/${CONTAINER_NAME}:/data/db
