#check .env file for variables/values
version: "3.9"
services:
    web:
        build:
            context: ../../app.webapi/
            dockerfile: ./Dockerfile-Debug
        image: "${IMAGE_NAME}"
        container_name: "${CONTAINER_NAME}"
        ports:
            - "${PORT_MAP}"
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            #ConnectionStrings__SampleDb: CONNECTION_STRING_NOT_PRESENT_FROM_DOCKER_COMPOSE
        