#check .env file for variables/values
version: "3.9"
services:
    db:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: "${IMAGE_NAME}"
        container_name: "${CONTAINER_NAME}"
        ports:
            - "${PORT_MAP}"
        volumes:
            - mssqldata:/var/opt/mssql
volumes:
  mssqldata: