version: "3.7"
services:
  api:
    image: demo-rest-api-node-js:test
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:test@db:5432/demo
      - PORT=3000
    depends_on:
      - db

  db:
    image: demo-rest-api-ops-db:test
    environment:
      - POSTGRES_PASSWORD=test
    ports:
      - "6432:5432"
